const KEY='danielmente-data-v1';
const goals={sleep:8,weight:230,movement:30,eating:4};
const colors={sleep:'#7457ff',weight:'#ff4d8d',movement:'#13b68a',screen:'#ff9f1c',eating:'#1f8cff'};
const defaultData={entries:{},settings:{screenGoalMinutes:240,notifications:false},reports:{}};
let data=load();
let deferredPrompt;
const $=s=>document.querySelector(s);
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll();}
function entry(date){return data.entries[date]||(data.entries[date]={});}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function sleepHours(bed,wake){if(!bed||!wake)return null;let [bh,bm]=bed.split(':').map(Number),[wh,wm]=wake.split(':').map(Number);let mins=(wh*60+wm)-(bh*60+bm);if(mins<=0)mins+=1440;return +(mins/60).toFixed(2)}
function dateRange(n=14,end=today()){const arr=[];const d=new Date(end+'T12:00:00');for(let i=n-1;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);arr.push(x.toISOString().slice(0,10))}return arr}
function movingAverage(values,window=7){return values.map((_,i)=>{const slice=values.slice(Math.max(0,i-window+1),i+1).filter(v=>v!=null);return slice.length?slice.reduce((a,b)=>a+b,0)/slice.length:null})}
function scoreForDate(date){const e=data.entries[date]||{};let parts=[];if(e.sleepHours!=null)parts.push(Math.min(100,e.sleepHours/8*100));if(e.movement!=null)parts.push(Math.min(100,e.movement/30*100));if(e.eatingScore!=null)parts.push(e.eatingScore/4*100);if(e.screenMinutes!=null)parts.push(Math.max(0,Math.min(100,(data.settings.screenGoalMinutes/e.screenMinutes)*100)));return parts.length?Math.round(parts.reduce((a,b)=>a+b,0)/parts.length):0}
function renderQuick(){const e=data.entries[$('#entryDate').value]||{};const items=[
 ['Sleep',e.sleepHours!=null?e.sleepHours.toFixed(1)+' h':'—','8 h',colors.sleep],
 ['Weight',e.weight!=null?e.weight.toFixed(1)+' lb':'—','Goal 230',colors.weight],
 ['Move',e.movement!=null?e.movement+' min':'—','30 min',colors.movement],
 ['Screen',e.screenMinutes!=null?formatMinutes(e.screenMinutes):'—','Lower is better',colors.screen],
 ['Eating',e.eatingScore!=null?e.eatingScore+'/4':'—','Ideal choices',colors.eating]
 ];
 $('#quickGrid').innerHTML=items.map(x=>`<div class="quick-card" style="--accent:${x[3]}"><span>${x[0]}</span><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('');
 const sc=scoreForDate($('#entryDate').value);$('#dailyScore').textContent=sc;$('#dailyRing').style.setProperty('--score',sc);$('#heroMessage').textContent=sc>=85?'Excellent balance today.':sc>=65?'A solid day—keep building.':sc>0?'A few small wins can lift the day.':'Log a habit to begin your day.';
}
function formatMinutes(m){return `${Math.floor(m/60)}h ${m%60}m`}
function renderInputs(){const e=data.entries[$('#entryDate').value]||{};$('#bedTime').value=e.bed||'';$('#wakeTime').value=e.wake||'';$('#weightInput').value=e.weight??'';$('#movementInput').value=e.movement??'';$('#screenHours').value=e.screenMinutes!=null?Math.floor(e.screenMinutes/60):'';$('#screenMinutes').value=e.screenMinutes!=null?e.screenMinutes%60:'';renderEating(e.eating||{});updateBadges(e)}
function updateBadges(e){$('#sleepToday').textContent=e.sleepHours!=null?e.sleepHours.toFixed(1)+' h':'Not logged';$('#weightToday').textContent=e.weight!=null?e.weight.toFixed(1)+' lb':'Not logged';$('#movementToday').textContent=e.movement!=null?e.movement+' min':'Not logged';$('#screenToday').textContent=e.screenMinutes!=null?formatMinutes(e.screenMinutes):'Not logged';$('#eatingToday').textContent=e.eatingScore!=null?e.eatingScore+'/4':'Not logged'}
const questions=[['breakfast','Protein shake for breakfast?',true],['stops','Stops after work?',false],['snacks','Snacks after kids’ bedtime?',false],['lunch','Lunch for tomorrow prepped?',true]];
function renderEating(ans){$('#eatingQuestions').innerHTML=questions.map(([k,q])=>`<div class="question"><p>${q}</p><div class="segmented" data-q="${k}"><button data-v="true" class="${ans[k]===true?'active':''}">Yes</button><button data-v="false" class="${ans[k]===false?'active':''}">No</button></div></div>`).join('');document.querySelectorAll('.segmented button').forEach(b=>b.onclick=()=>{const box=b.parentElement;box.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function renderWeightGoals(){const latest=Object.entries(data.entries).filter(([,e])=>e.weight!=null).sort(([a],[b])=>a.localeCompare(b)).at(-1)?.[1].weight;const milestones=[260,250,240,230];$('#weightGoalTrack').innerHTML=milestones.map(m=>`<span class="goal-dot ${latest!=null&&latest<=m?'reached':''}" title="${m} lb"></span>`).join('');let next=milestones.find(m=>latest==null||latest>m)||230;$('#nextWeightGoal').textContent=next+' lb'}
function drawChart(canvasId,values,opts={}){const c=$(canvasId),ctx=c.getContext('2d'),ratio=devicePixelRatio||1,w=c.clientWidth,h=180;c.width=w*ratio;c.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const valid=values.flatMap(s=>s.data).filter(v=>v!=null);if(!valid.length){ctx.fillStyle='#98a2b3';ctx.font='14px -apple-system';ctx.fillText('No data yet',14,30);return}let min=opts.min??Math.min(...valid),max=opts.max??Math.max(...valid);if(min===max){min-=1;max+=1}const pad={l:34,r:12,t:16,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;ctx.strokeStyle='#e4e7ec';ctx.lineWidth=1;for(let i=0;i<4;i++){let y=pad.t+ch*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke()}const x=i=>pad.l+(values[0].data.length===1?cw/2:cw*i/(values[0].data.length-1));const y=v=>pad.t+ch-(v-min)/(max-min)*ch;values.forEach((s,si)=>{ctx.strokeStyle=s.color;ctx.lineWidth=si?2:3;ctx.setLineDash(si?[6,5]:[]);ctx.beginPath();let started=false;s.data.forEach((v,i)=>{if(v==null){started=false;return}if(!started){ctx.moveTo(x(i),y(v));started=true}else ctx.lineTo(x(i),y(v))});ctx.stroke();ctx.setLineDash([]);if(!si)s.data.forEach((v,i)=>{if(v==null)return;ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(x(i),y(v),3,0,Math.PI*2);ctx.fill()})});ctx.fillStyle='#98a2b3';ctx.font='10px -apple-system';const labels=opts.labels||[];[0,Math.floor((labels.length-1)/2),labels.length-1].forEach(i=>{if(i>=0&&labels[i])ctx.fillText(labels[i],Math.max(0,x(i)-12),h-8)});ctx.fillText((max).toFixed(opts.decimals??0),2,pad.t+4);ctx.fillText((min).toFixed(opts.decimals??0),2,pad.t+ch)}
function renderCharts(){const ds=dateRange(14),labels=ds.map(fmtDate);const vals=key=>ds.map(d=>data.entries[d]?.[key]??null);const sleep=vals('sleepHours');drawChart('#sleepChart',[{data:sleep,color:colors.sleep},{data:movingAverage(sleep),color:'#111827'}],{labels,min:0,max:12,decimals:0});const wt=vals('weight');drawChart('#weightChart',[{data:movingAverage(wt,7),color:colors.weight}],{labels,decimals:0});const mov=vals('movement');drawChart('#movementChart',[{data:mov,color:colors.movement},{data:movingAverage(mov),color:'#111827'}],{labels,min:0});const scr=vals('screenMinutes').map(v=>v==null?null:v/60);drawChart('#screenChart',[{data:scr,color:colors.screen},{data:movingAverage(scr),color:'#111827'}],{labels,min:0,decimals:1});const eat=vals('eatingScore');drawChart('#eatingChart',[{data:eat,color:colors.eating},{data:movingAverage(eat),color:'#111827'}],{labels,min:0,max:4,decimals:0})}
function weekDates(endDate=today()){const d=new Date(endDate+'T12:00:00'),day=d.getDay();d.setDate(d.getDate()-day);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()-6+i);return x.toISOString().slice(0,10)})}
function generateReport(){const days=weekDates(),scores=days.map(scoreForDate),logged=scores.filter(Boolean),overall=logged.length?Math.round(logged.reduce((a,b)=>a+b,0)/7):0;const avg=k=>{const a=days.map(d=>data.entries[d]?.[k]).filter(v=>v!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};const sleep=avg('sleepHours'),move=avg('movement'),eat=avg('eatingScore'),screen=avg('screenMinutes');const suggestions=[];if(sleep==null||sleep<7.5)suggestions.push('Move bedtime earlier by 15–30 minutes and prepare the CPAP before winding down.');if(move==null||move<30)suggestions.push('Use a 10-minute minimum: three short movement blocks still reach the daily goal.');if(eat==null||eat<3)suggestions.push('Prioritize tomorrow’s lunch prep and create a clear “kitchen closed” cue after the kids’ bedtime.');if(screen!=null&&screen>data.settings.screenGoalMinutes)suggestions.push('Charge the phone away from your usual evening seat and choose a specific offline activity.');if(!suggestions.length)suggestions.push('Maintain the current routine and focus on consistency rather than adding new goals.');const grade=overall>=90?'A':overall>=80?'B':overall>=70?'C':overall>=60?'D':'Needs focus';$('#weeklyScore').textContent=overall;$('#weeklyRing').style.setProperty('--score',overall);$('#reportTitle').textContent=`${grade} · ${fmtDate(days[0])}–${fmtDate(days[6])}`;$('#reportContent').innerHTML=`<div class="report-item"><strong>Week score: ${overall}/100</strong>${logged.length} of 7 days contained scored entries.</div><div class="report-item"><strong>Averages</strong>Sleep ${sleep==null?'—':sleep.toFixed(1)+' h'} · Movement ${move==null?'—':Math.round(move)+' min'} · Eating ${eat==null?'—':eat.toFixed(1)+'/4'} · Screen ${screen==null?'—':formatMinutes(Math.round(screen))}</div><div class="report-item"><strong>Week ahead</strong>${suggestions.map(s=>'• '+s).join('<br>')}</div>`;data.reports[days[6]]={score:overall,suggestions,generated:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(data));return overall}
function renderAll(){renderQuick();renderInputs();renderWeightGoals();renderCharts();generateReport()}

document.addEventListener('click',e=>{const saveType=e.target.dataset.save;if(!saveType)return;const d=$('#entryDate').value,e1=entry(d);if(saveType==='sleep'){e1.bed=$('#bedTime').value;e1.wake=$('#wakeTime').value;e1.sleepHours=sleepHours(e1.bed,e1.wake)}if(saveType==='weight')e1.weight=parseFloat($('#weightInput').value)||null;if(saveType==='movement')e1.movement=Math.max(0,parseInt($('#movementInput').value)||0);if(saveType==='screen')e1.screenMinutes=(parseInt($('#screenHours').value)||0)*60+(parseInt($('#screenMinutes').value)||0);if(saveType==='eating'){e1.eating={};questions.forEach(([k])=>{const active=document.querySelector(`.segmented[data-q="${k}"] .active`);if(active)e1.eating[k]=active.dataset.v==='true'});e1.eatingScore=questions.reduce((n,[k,,ideal])=>n+(e1.eating[k]===ideal?1:0),0)}save();toast('Saved')});
$('#entryDate').value=today();$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#entryDate').onchange=()=>{renderInputs();renderQuick()};$('#refreshReport').onclick=()=>{generateReport();toast('Weekly report updated')};$('#jumpLog').onclick=e=>{e.preventDefault();document.querySelector('.section-heading').scrollIntoView()};
$('#screenCsv').onchange=async e=>{const text=await e.target.files[0].text();const lines=text.trim().split(/\r?\n/);for(const line of lines.slice(1)){const [date,hours,minutes]=line.split(',').map(x=>x.trim());if(/^\d{4}-\d{2}-\d{2}$/.test(date))entry(date).screenMinutes=(+hours||0)*60+(+minutes||0)}save();toast('Screen Time CSV imported')};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`danielmente-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();toast('Data restored')}catch{toast('Could not restore file')}};
$('#resetBtn').onclick=()=>{if(confirm('Delete all danielmente data from this device?')){data=structuredClone(defaultData);save();toast('Data reset')}};
$('#notifyBtn').onclick=async()=>{if(!('Notification'in window)){toast('Notifications are not supported here');return}const p=await Notification.requestPermission();if(p==='granted'){data.settings.notifications=true;save();new Notification('danielmente',{body:'Sunday reports are enabled. Open the app each Sunday to generate your weekly report.'});toast('Notifications enabled')}else toast('Notification permission was not granted')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else toast('In Safari, use Share → Add to Home Screen')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
if(new Date().getDay()===0&&data.settings.notifications&&Notification.permission==='granted'){setTimeout(()=>new Notification('Your danielmente weekly report is ready',{body:'Open the app to review your score and plan the week ahead.'}),1500)}
renderAll();
